### PR TITLE
Create initial .editorconfig

### LINKED ISSUE #3: add .editorconfig to this repo
This is a proposal.
I think [editorconfig](http://editorconfig.org/) would be useful in [this situation](https://github.com/symdiff/grunt-symdiff/pull/1#discussion_r30274585).

### PR DESCRIPTION
**Pull request by matiassingers**
Closes #3

### CODE REVIEW

**Comment by prayerslayer** [comment]
I’d prefer a [.jscsrc](http://jscs.info/) file along with an appropriate Grunt taksk.

**Comment by matiassingers** [comment]
There are plugins for most editors out there, and I would just add it as part of the `CONTRIBUTING.md` so people see it before contributing.

See list of plugins here: [EditorConfig](http://editorconfig.org/#download)

---

I guess JSCS can handle indentation as well, but it's really more for code style like spaces before/after braces etc. right?

NB. it's normal to use 2-spaces indendation for JS :wink:

**Comment by prayerslayer** [comment]
> NB. it's normal to use 2-spaces indendation for JS

[Citation needed.]

> I guess JSCS can handle indentation as well, but it's really more for code style like spaces before/after braces etc. right?

You could say it’s more flexible and less work for people because it can fix some of the errors automatically. So I’d still rather have a `.jscsrc` :)

**Comment by matiassingers** [comment]
Right `.jscsrc` might be a better choice for this project ;)

I personally prefer [feross/standard](https://github.com/feross/standard)

**Pull request closed without merging**
